### ISSUE TITLE
Invalid cert

### ISSUE THREAD

**Issue by ghost** [rwengine/rwengine.github.io#5]
```
openrw.org uses an invalid security certificate.
The certificate is only valid for the following names:
*.github.com, github.com, *.github.io, github.io
```

**Comment by danhedron** [comment]
I've contacted GitHub support about the issue with HTTPS not being available for the domain. I've received the solution but it requires DNS updates.

Should be resolved in a few days.

**Comment by danhedron** [comment]
HTTPS works now.
